### ISSUE TITLE
Doesnt work in online lobbies

### ISSUE THREAD

**Issue by cat64k** [jamesy012/OpenPlanet-BestCheckpoints#2] opened 2022-02-15 17:35 UTC
Times dont update if you are playing on online server, except for the first lap you drive.

In singleplayer plugin works fine.

**Comment by cat64k** [comment] 2022-02-17 22:12
i just tested your code snippet for a few minutes, seems to work, nice work!

**Comment by jamesy012** [comment] 2022-02-17 22:23
oh awesome, sorry I forgot to write a comment here afterwards 

thanks for testing it, i'll close the issue
I'll hopefully make a new version on openplanet later in the month

**Closed as completed by jamesy012** 2022-02-17 22:23 UTC

**Comment by cat64k** [comment] 2022-02-18 17:24
hi jamesy012

i hope you still read this, even if you closed the topic. Now i got some occation in multiplayer, where it's still writing negative times into the checkpoints (with that code snippet above).

It happens sometimes, if i do a restart without finishing the run. I need further testing to spot more regularities.  

Maybe reopen that ticket?

![negative CP times](https://user-images.githubusercontent.com/47006805/154732240-941d4df1-88df-4a64-9f87-9881d2e0554b.png)

**Comment by cat64k** [comment] 2022-02-18 17:40
i think i've found the regularity:

So if you dont finish your first run on the map, but crossed some cp the negative time will be written in the cptime after the last cp you crossed.

**Comment by jamesy012** [comment] 2022-02-19 10:26
hmm I tried to reproduce this negative time thing you mentioned when playing maps on the track of the day map test server this morning and couldn't get it to trigger

I might just add something to invalidate/clear all the times if a negative time gets added
not a great solution but since I cant reproduce it I think it'll work fine, I'll do it tomorrow morning

probably a bit late but there's an option in the settings to reset that maps data so you can remove that negative time

**Comment by cat64k** [comment] 2022-02-19 22:34
It happens only if your first run at all of a track isnt completed on multiplayer server.

steps To reproduce: 
join a multiplayer server, where you dont have cp-times (or just reset the data)
drive the map until you cross a cp (any cp)
reset your car to the start

here a link to the youtube video (i moved your plugin to the top right)
https://youtu.be/dcpKmOjSoaM

**Comment by jamesy012** [comment] 2022-02-19 23:52
I remember seeing this before releasing the plugin, my change just before should resolve it, 
Not sure how your still getting it though..

**Comment by cat64k** [comment] 2022-02-20 16:37
it might be fixed with that other issue, idk. but with the change of those few lines it happens everytime for me.
